name: Crawl NLB Data
on:
  schedule:
    - cron: "12 20 * * *" # 04:12 (HKT) daily
  workflow_dispatch:

jobs:
  Crawl-NLB-Data:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Install uv and set up Python
        uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: '3.14'
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Crawl NLB raw data
        env:
          REQUEST_LIMIT: "6"
        run: uv run python ./crawling/nlb_crawl.py --force

      - name: Publish NLB raw data to "latest-nlb" release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-nlb
          name: Latest NLB raw data
          body: Automatically updated by the Crawl NLB Data workflow.
          files: |
            data/nlb.raw.routeList.json
            data/nlb.raw.routeStopList.json
            data/nlb.raw.stopList.json

      - name: Upload NLB raw data to S3
        env:
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          pids=()
          aws s3 cp data/nlb.raw.routeList.json s3://${{ secrets.AWS_S3_BUCKET }}/transport/nlb/nlb.raw.routeList.json & pids+=($!)
          aws s3 cp data/nlb.raw.routeStopList.json s3://${{ secrets.AWS_S3_BUCKET }}/transport/nlb/nlb.raw.routeStopList.json & pids+=($!)
          aws s3 cp data/nlb.raw.stopList.json s3://${{ secrets.AWS_S3_BUCKET }}/transport/nlb/nlb.raw.stopList.json & pids+=($!)
          for pid in "${pids[@]}"; do wait "$pid"; done

      - name: Archive NLB raw data
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: NLB Raw Files
          retention-days: 14
          path: |
            data/nlb.raw.routeList.json
            data/nlb.raw.routeStopList.json
            data/nlb.raw.stopList.json
